### ISSUE TITLE
ECC compatible with OpenSSL?

### ISSUE THREAD

**Issue by rrottmann** [wirenboard/atecc-util#10]
In an IoT scenario where there is a web service where clients want to authenticate before uploading sensor data, is it possible to communicate with a public ecc key e.g. created by OpenSSL?  Or do both need a secure element?

**Comment by evgeny-boger** [comment]
Of course it is compatible with OpenSSL. Please see https://github.com/wirenboard/cryptoauth-openssl-engine or Microchip's https://github.com/MicrochipTech/cryptoauth-openssl-engine
