### ISSUE TITLE
release tags

### ISSUE THREAD

**Issue by bernardoaraujor** [wirenboard/atecc-util#6]
I'm integrating the project into OpenEmbedded.
It would be interesting to have release tags on the repo.

**Comment by evgeny-boger** [comment]
I'm sorry, I'm not familiar with OpenEmbeded. Is it ok if I just create "v0.4.3" tag manually for the moment?

**Comment by bernardoaraujor** [comment]
on current master HEAD?

**Comment by evgeny-boger** [comment]
yes. The master branch is considered stable one in this project.

**Comment by bernardoaraujor** [comment]
ok thanks
